### PR TITLE
Add support for logs

### PR DESCRIPTION
**Pull request by jjatria**
~~Note that this branch will be rebased on a periodic basis to stay on top of changes in main. If you are checking this out early, do remember to do `git pull -r` to avoid conflicts.~~

### CODE REVIEW

**Comment by jjatria** [comment]
This branch is ready to be merged

**Comment by jjatria** [comment]
@tm604 Do you think you might be able to give this PR a look?

I've been using this on a test environment, and I'm now happy with the way it looks. I think this can be merged and released to CPAN safely, since nothing will be using it.

After this is out, we can think about the order in which the API (https://github.com/jjatria/perl-opentelemetry/pull/7) and the SDK (https://github.com/jjatria/perl-opentelemetry-sdk/pull/6) PRs for logs support can be merged and released, perhaps increasing the required versions.

**Comment by tm604** [comment]
This sounds great, thanks - I'll try out the branch to see if any new or exciting issues appear, but on first glance it's looking good :+1:

**Comment by jjatria** [comment]
This was released to CPAN as 0.016001-TRIAL, but I expect it to be bumped to 0.017 in the next coming weeks.

**Pull request merged**
