### PR TITLE
Trace and Span IDs are hex encoded in JSON; timestamps are integers

### PR DESCRIPTION
**Pull request by abh**
(This makes the OTLP exporter able to export my test traces to the otel collector)

### CODE REVIEW

**Comment by abh** [comment]
The tests fail because Local::Span doesn't have the hex methods. I didn't fix that because I wasn't sure if this was right in the first place.

**Comment by jjatria** [comment]
Ah, well spotted. Thanks! I think I misread the spec, and was explicitly base64-encoding them when the spec says the exact opposite.

As for the test, if we are now relying on `hex_{trace,span}_id` then we should add them to Local::Span in the test, so they pass. Could you do that?

Also: if we are no longer going to need the `encode_id` method we can remove it entirely, which I think would allow us to drop the dependency on MIME::Base64 (ie. we can remove it from the cpanfile). Makefile.PL is autogenerated, so I wouldn't worry too much about that.

If you'd rather I do these things, I can push them to your branch. Let me know.

**Comment by jjatria** [comment]
Actually, now I'm a little confused. From https://github.com/open-telemetry/oteps/blob/main/text/0122-otlp-http-json.md#json-mapping:

> JSON Mapping
> 
> Use proto3 standard defined [JSON Mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) for mapping between protobuf and json. `trace_id` and `span_id` is base64 encoded in OTLP/HTTP+JSON, not hex.

---

EDIT: Nevermind, I was getting confused again. I suspect there's a difference between the OTEP and the actual spec, since https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding says the opposite (to use hex, not base64).

**Comment by tm604** [comment]
I found there's one other minor change in JSON.pm that's needed before Jægertracing will accept HTTP+JSON - the `stringValue` fields (e.g. pid) have to be strings, so wrapping in `""` is enough to make things happy.

```
diff --git a/lib/OpenTelemetry/Exporter/OTLP/Encoder/JSON.pm b/lib/OpenTelemetry/Exporter/OTLP/Encoder/JSON.pm
index e681194..f6496cf 100644
--- a/lib/OpenTelemetry/Exporter/OTLP/Encoder/JSON.pm
+++ b/lib/OpenTelemetry/Exporter/OTLP/Encoder/JSON.pm
@@ -48,7 +48,7 @@ class OpenTelemetry::Exporter::OTLP::Encoder::JSON {
         }
 
         # TODO: not strings
-        return { stringValue => $v };
+        return { stringValue => "$v" };
     }
 
     method encode_resource ( $resource ) {
```

**Comment by jjatria** [comment]
I've cherry-picked this change as 7c33d7a70208e38089a808548e42776ac53d9cf2, modified slightly to include the things discussed above.

Thanks for the contribution!

**Comment by abh** [comment]
Thank you; apologies I did t get back to it more promptly! The spec is super confusing; it sure makes me appreciate the IETF process output / RFC format. One thing I wasn’t sure about (and why I didn’t remove the encode functions was if the proto format and the json format needed different encodings of the IDs.

**Comment by jjatria** [comment]
No problem! We all have have other things to do. :)

As for `encode_id`, the JSON and Protobuf encodings _do_ use different formats, but all of the places that use the ID put it in fields that will (annoyingly) have different casings in JSON (camelCase) and Protobuf (snake_case). So those need to be repeated for each.

Incidentally, I just noticed that I missed a spot in the JSON encoder: https://github.com/jjatria/perl-opentelemetry-exporter-otlp/blob/7170056c3eab24aa8ccab4e9cb337d9d08a6fba2/lib/OpenTelemetry/Exporter/OTLP/Encoder/JSON.pm#L100 

:frowning_face: 

---

The casing of `parent_span_id` was fixed in 0.015, which should be on CPAN shortly.

**Pull request closed without merging**
